superpoint:
  input_tensor_names:
    - "image"
  output_tensor_names:
    - "scores"
    - "descriptors"
  max_keypoints: 2048
  keypoint_threshold: 0.005
  remove_borders: 4
  dla_core: -1
  onnx_file: "offical_sp.onnx"
  engine_file: "offical_sp.engine"

superpoint_lightglue:
  input_tensor_names:
    - "keypoints0"
    - "keypoints1"
    - "descriptors0"
    - "descriptors1"
  output_tensor_names:
    - "scores"
  image_width: 640
  image_height: 480
  filter_threshold: 0.1
  depth_confidence: 0.95
  width_confidence: 0.99
  dla_core: -1
  onnx_file: "offical_lg.onnx"
  engine_file: "offical_lg.engine"
